//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.03 at 09:17:53 AM CEST 
//


package fr.datasyscom.iom.submit;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for destinationEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="destinationEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Queue"/>
 *     &lt;enumeration value="Worflow"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "destinationEnum")
@XmlEnum
public enum DestinationEnum {

    @XmlEnumValue("Queue")
    QUEUE("Queue"),
    @XmlEnumValue("Worflow")
    WORFLOW("Worflow");
    private final String value;

    DestinationEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DestinationEnum fromValue(String v) {
        for (DestinationEnum c: DestinationEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
