//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.03 at 09:17:53 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.datasyscom.fr/iom/submit", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package fr.datasyscom.iom.submit;
