//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.03 at 09:17:53 AM CEST 
//


package fr.datasyscom.iom.submit;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for parametreEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="parametreEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="text"/>
 *     &lt;enumeration value="int"/>
 *     &lt;enumeration value="date"/>
 *     &lt;enumeration value="boolean"/>
 *     &lt;enumeration value="choice"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "parametreEnum")
@XmlEnum
public enum ParametreEnum {

    @XmlEnumValue("text")
    TEXT("text"),
    @XmlEnumValue("int")
    INT("int"),
    @XmlEnumValue("date")
    DATE("date"),
    @XmlEnumValue("boolean")
    BOOLEAN("boolean"),
    @XmlEnumValue("choice")
    CHOICE("choice");
    private final String value;

    ParametreEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ParametreEnum fromValue(String v) {
        for (ParametreEnum c: ParametreEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
