//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.03 at 10:07:07 AM CEST 
//


package fr.datasyscom.iom.submit;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for parametreVisibility.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="parametreVisibility">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="modifiable"/>
 *     &lt;enumeration value="show"/>
 *     &lt;enumeration value="hidden"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "parametreVisibility")
@XmlEnum
public enum ParametreVisibility {

    @XmlEnumValue("modifiable")
    MODIFIABLE("modifiable"),
    @XmlEnumValue("show")
    SHOW("show"),
    @XmlEnumValue("hidden")
    HIDDEN("hidden");
    private final String value;

    ParametreVisibility(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ParametreVisibility fromValue(String v) {
        for (ParametreVisibility c: ParametreVisibility.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
